apply plugin: 'com.android.library'

import jsettlers.shaders.compile.ShaderCompilationTask

def shaderDefinitionDir = 'src/main/glsl/'
def shaderJavaOutputDir = 'src/generated/java'
def shaderResOutputDir = 'src/generated/resources'

android {
    namespace = 'go.graphics.android'
    compileSdk = rootProject.ext.androidCompileSdkVersion

    defaultConfig {
        minSdk = rootProject.ext.androidMinSdkVersion
        targetSdk = rootProject.ext.androidTargetSdkVersion
        multiDexEnabled = true
    }

    buildTypes {
        release {
            minifyEnabled = false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
        }
    }

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src/main/java']
            resources.srcDirs = ['src/main/resources', shaderResOutputDir]
            res.srcDirs = ['src/main/res']
            assets.srcDirs = ['assets']
        }
    }

    compileOptions {
        coreLibraryDesugaringEnabled = true

        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
    }
}

dependencies {
    implementation project(':go.graphics')

    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:2.0.4'
}


clean {
    delete file(shaderJavaOutputDir)
    delete file(shaderResOutputDir)
}

task compileShaders(type: ShaderCompilationTask) {
    inputDirectory = file(shaderDefinitionDir).toPath()
    generatedSourcesDirectory = file(shaderJavaOutputDir).toPath()
    generatedResourcesDirectory = file(shaderResOutputDir).toPath()
}

// every task of a variant runs after preBuild, so all of them can use the generated shaders
tasks.named('preBuild').configure {
    dependsOn compileShaders
}
